### ISSUE TITLE
agile-device-execute not works 

### ISSUE THREAD

**Issue by jordiescudero** [Agile-IoT/agile-node-red-nodes#3]
Hi,
the current implementation of the "agile-device-execute" node not works like "agile-device-read".
Currently is not possible to select a device like the read (or subscribe) node, seems that the "execute.html" not have the same code of the "read.html" in order to retrive the device information throught the http api of AGILE.
Regards

**Comment by cskiraly** [comment]
fixed in https://github.com/Agile-IoT/agile-node-red-nodes/commit/3f8db65fcd792a0c6556365b4b11327e388a17cb and https://github.com/Agile-IoT/agile-node-red-nodes/commit/f40cab4e576e70f122ba64bc775d9cfee04be3e9
