### ISSUE TITLE
Changes on the AGILE device subscribe do not take place

### ISSUE THREAD

**Issue by nopbyte** [Agile-IoT/agile-node-red-nodes#4]
When I create a node to subscribe to a sensor (IT-sensor tag or dummy data) and bind it to a debug node everything works fine.

However, when I delete the subscribe node from the flow, and re-deploy, the data is still being printed to the debug tab. If I modify the sensor and re-deploy than I get both inputs in the debug tab, even though I am seeing only one subscribe sensor. This seems like a bug?

**Comment by koustabhdolui** [comment]
@nopbyte This was occurring as the websocket was still open even when the node is redeployed. I fixed it. Please check if the issue persists!

**Comment by cskiraly** [comment]
fixed in https://github.com/Agile-IoT/agile-node-red-nodes/commit/0ddaaf75f31609255724584b21a8eb8f50ae6691

**Comment by nopbyte** [comment]
@cskiraly @koustabhdolui  is there an easy way to test this?  I guess you should have updated the module in https://github.com/Agile-IoT/agile-nodered to trigger a new build on docker?

**Comment by koustabhdolui** [comment]
@nopbyte Updated the submodule of agile-node-red-nodes to the latest commit on agile-nodered! 
Another way to test it, would be to clone the agile-node-red-nodes repository and link it to a local instance of node-red using npm link <module-name>

**Comment by nopbyte** [comment]
nice work! it is indeed fixed now.
